/*
ENTRY NUMBER SEVENTEEN-AND-A-HALF
DARK
DARKER
YET DARKER
THE DARKNESS KEEPS GROWING
THE SHADOWS CUTTING DEEPER
PHOTON READINGS NEGATIVE
LACK OF LIGHT ENERGY READINGS POSITIVE
PIZZA TIME IMMINENT
THIS NEXT EXPERIMENT
SEEMS
VERY
VERY
INTERESTING
...
AT LEAST, THAT SEEMS TO BE THE CASE
THIS IS WHAT HAPPENS WHEN YOU TRY TO FILL UP AN UNUSED COMPONENT
JUST FOR A SILLY EASTER EGG THAT I'M NOT SURE ANYONE WILL NOTICE
ISN'T THAT RIGHT, YOU TWO
*/